services:
#  keycloak:
#    image: quay.io/keycloak/keycloak:26.0.4
#    ports:
#      - "8080:8080"
#    environment:
#      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
#      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
#    command: start-dev
#    container_name: keycloak_server

  db_users:
    image: pgvector/pgvector:pg15
    container_name: db_users
    environment:
      POSTGRES_DB: db_users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5435:5432
